# Generated by Django 5.2.6 on 2025-11-14 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=35)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('sequence', '순차'), ('selection', '조건'), ('repetition', '반복')], max_length=10)),
                ('title', models.CharField(max_length=25)),
                ('question_text', models.TextField()),
                ('question_image', models.URLField()),
                ('ai_prompt', models.TextField()),
                ('answer_assets', models.JSONField(default=dict)),
                ('badge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mission', to='missions.badge')),
            ],
        ),
    ]
