# Generated by Django 5.2.6 on 2025-11-08 06:28

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('image', models.ImageField(upload_to='badge/image')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('sequence', '순차'), ('selection', '조건'), ('repetition', '반복')], max_length=10)),
                ('title', models.CharField(max_length=25)),
                ('question_text', models.TextField()),
                ('question_image', models.ImageField(upload_to='mission/question_image')),
                ('ai_prompt', models.TextField()),
                ('answer_assets', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict), size=None)),
                ('badge', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='mission', to='missions.badge')),
            ],
        ),
    ]
