# Generated by Django 5.2.6 on 2025-11-14 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=35)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=2)),
                ('theme', models.CharField(max_length=10)),
                ('badge', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='chapter', to='missions.badge')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=50)),
                ('image', models.URLField()),
                ('question_text', models.TextField()),
                ('question_image', models.URLField()),
                ('answer_assets', models.JSONField(default=dict)),
                ('ai_prompt', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='missions.chapter')),
            ],
        ),
    ]
