# Generated by Django 5.2.6 on 2025-11-12 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='description',
            field=models.CharField(default='', max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='badge',
            name='id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mission',
            name='badge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mission', to='missions.badge'),
        ),
    ]
