# Generated by Django 5.2.6 on 2025-11-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='question_hint',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
