# Generated by Django 5.2.6 on 2025-11-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_badge_description_alter_badge_id_alter_mission_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='question_image',
            field=models.URLField(),
        ),
    ]
