# Generated by Django 5.2.6 on 2025-11-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_mission_question_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='question_hint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
