# Generated by Django 5.2.6 on 2025-11-08 06:28

import django.db.models.deletion
import django_nanoid.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionHistory',
            fields=[
                ('id', django_nanoid.models.NANOIDField(alphabetically=None, prefix=None, primary_key=True, secure_generated=True, serialize=False, size=None, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('is_solved', models.BooleanField(default=False)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_history', to='missions.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.IntegerField(choices=[(0, '유저'), (1, 'AI')])),
                ('content', models.TextField()),
                ('solution_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='solutions.solutionhistory')),
            ],
        ),
    ]
