# Generated by Django 5.2.6 on 2025-11-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solutionhistory',
            old_name='solved_at',
            new_name='updated_at',
        ),
    ]
