# Generated by Django 5.2.6 on 2025-11-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_rename_solved_at_solutionhistory_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
